language: python
python:
  - "3.6"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
before_install:
  - pip install pipenv
install:
  - pipenv install
script:
  - docker build -t readthedocs/build:master .
  - pipenv run pytest -m master

branches:
  only:
    - master
    - releases/6.x
